# Generated by Django 3.2.12 on 2022-02-15 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("huey_monitor", "0009_changed_task_and_signal_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskmodel",
            name="create_dt",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="(will be set automatically)",
                verbose_name="Create date",
            ),
            preserve_default=False,
        ),
    ]
